# Generated by Django 3.2.3 on 2021-05-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_logindetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='conatctNumber',
            new_name='contactNumber',
        ),
    ]
